title:              Rui Vergani Neto
email:              ruiverganineto@example.com
description:        This is a blog created by Computer Science student at the University of Staffordshire, the purpose is to provide some content regarding my degree, also another possibility of learning some extra IT related content. 
author:             Rui Vergani Neto
baseurl:            ""
url:                "https://ruivergani.github.io"


collections:
  cards:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

paginate: 9
paginate_path: /home:num/
plugins:
  - jekyll-paginate


gems: [jekyll-paginate]